"""Generate per-dataset parse plans from ``docs/inspection_report.md``."""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORT_PATH = ROOT / "docs" / "inspection_report.md"
OUTPUT_DIR = ROOT / "config" / "parse_plans"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from etl.config import dataset_for_program_id  # noqa: E402


def _slug_from_workbook(workbook: str) -> str:
    """Derive a stable output dataset slug from workbook filename.

    e.g. '51293-2021-02-childnutrition.xlsx' -> 'childnutrition_2021_02'
    """
    stem = re.sub(r"\.xlsx$", "", workbook, flags=re.IGNORECASE)
    # typical pattern: <id>-<year>-<month>-<program>[_suffix]
    m = re.match(r"^\d+[-_](\d{4})[-_](\d{2})[-_](.+)$", stem)
    if m:
        year, month, prog = m.group(1), m.group(2), m.group(3)
        prog_clean = re.sub(r"[^a-z0-9]+", "_", prog.lower()).strip("_")
        return f"{prog_clean}_{year}_{month}"
    return re.sub(r"[^a-z0-9]+", "_", stem.lower()).strip("_")


def _notes_for(sheet: dict) -> list[str]:
    notes = []
    if sheet.get("has_merged_cells"):
        notes.append("merged cells present — verify header parsing")
    if sheet.get("multiple_tables_flagged"):
        notes.append("multiple logical tables detected — may need manual split")
    if sheet["likely_first_data_row"] is None:
        notes.append("first data row could not be inferred — manual review needed")
    return notes


def _verification_target(workbook: str, sheet_name: str) -> str:
    stem = re.sub(r"\.xlsx$", "", workbook, flags=re.IGNORECASE)
    m = re.match(r"^\d+[-_](\d{4})[-_](\d{2})[-_](.+)$", stem)
    if m:
        year, month, prog = m.group(1), m.group(2), m.group(3)
        prog_clean = re.sub(r"[^a-z0-9]+", "-", prog.lower()).strip("-")
        return f"cbo-{prog_clean}-{year}-{month}"
    return re.sub(r"[^a-z0-9]+", "-", stem.lower()).strip("-")


def extract_json(report_text: str) -> list[dict]:
    m = re.search(r"## Machine-Readable Summary\s+```json\s+(.*?)```", report_text, re.DOTALL)
    if not m:
        sys.exit("ERROR: Could not find machine-readable JSON section in inspection report.")
    return json.loads(m.group(1))


def build_yaml_lines(profiles: list[dict]) -> list[str]:
    lines = [
        "# CBO Baseline Workbook Parse Plan",
        "# Generated by scripts/generate_parse_plans.py from docs/inspection_report.md",
        "# Fields: workbook, sheet, classification, include, output_dataset,",
        "#         header_rows, first_data_row, year_column_strategy, unit, notes, verification_target",
        "",
        "workbooks:",
    ]

    for wb in profiles:
        workbook = wb["workbook"]
        lines.append(f"  - workbook: {_yaml_str(workbook)}")
        lines.append(f"    sheets:")
        for sheet in wb["sheets"]:
            classification = sheet["classification"]
            include = classification == "data"
            slug = _slug_from_workbook(workbook)
            sheet_slug = re.sub(r"[^a-z0-9]+", "_", sheet["sheet_name"].lower()).strip("_")
            output_dataset = f"{slug}__{sheet_slug}" if not include else slug
            year_cols = sheet["fiscal_year_columns"]
            year_strategy = "column_index" if year_cols else "none"
            unit = sheet.get("unit_text") or ""
            notes_list = _notes_for(sheet)
            vtarget = _verification_target(workbook, sheet["sheet_name"])

            lines.append(f"      - sheet: {_yaml_str(sheet['sheet_name'])}")
            lines.append(f"        classification: {classification}")
            lines.append(f"        include: {'true' if include else 'false'}")
            if include:
                lines.append(f"        output_dataset: {_yaml_str(slug)}")
                lines.append(f"        verification_target: {_yaml_str(vtarget)}")
            else:
                lines.append(f"        output_dataset: null")
                lines.append(f"        verification_target: null")
            lines.append(f"        header_rows: {_yaml_str(sheet['likely_header_rows'])}")
            fdr = sheet["likely_first_data_row"]
            lines.append(f"        first_data_row: {fdr if fdr is not None else 'null'}")
            lines.append(f"        year_column_strategy: {year_strategy}")
            if year_cols:
                lines.append(f"        year_columns: [{', '.join(str(c) for c in year_cols)}]")
            else:
                lines.append(f"        year_columns: []")
            lines.append(f"        unit: {_yaml_str(unit)}")
            if notes_list:
                lines.append(f"        notes:")
                for note in notes_list:
                    lines.append(f"          - {_yaml_str(note)}")
            else:
                lines.append(f"        notes: []")

    lines.append("")
    return lines


def _yaml_str(value: str) -> str:
    """Wrap in double-quotes if value contains special YAML chars."""
    if not value:
        return '""'
    # Normalize whitespace — newlines in cell values must not break YAML
    value = " ".join(value.split())
    needs_quote = any(c in value for c in ':#{}[]|>&*!,?@`\'"\\') or value.startswith(" ") or value.endswith(" ")
    if needs_quote:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def _program_id(workbook: str) -> str:
    match = re.match(r"^(\d+)", workbook)
    return match.group(1) if match else "unregistered"


def main() -> int:
    report_text = REPORT_PATH.read_text(encoding="utf-8")
    profiles = extract_json(report_text)

    profiles_by_program: dict[str, list[dict]] = {}
    for profile in profiles:
        profiles_by_program.setdefault(_program_id(profile["workbook"]), []).append(profile)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for program_id, program_profiles in sorted(profiles_by_program.items()):
        dataset = dataset_for_program_id(program_id)
        filename = f"{dataset.key if dataset else program_id}.yml"
        output_path = OUTPUT_DIR / filename
        output_path.write_text(
            "\n".join(build_yaml_lines(program_profiles)),
            encoding="utf-8",
        )
        written.append(output_path)

    total_sheets = sum(len(wb["sheets"]) for wb in profiles)
    included = sum(
        1 for wb in profiles for s in wb["sheets"] if s["classification"] == "data"
    )
    print(f"Wrote {len(written)} parse plans to {OUTPUT_DIR}")
    print(f"  Workbooks: {len(profiles)}")
    print(f"  Sheets total: {total_sheets}")
    print(f"  Sheets included (data): {included}")
    print(f"  Sheets skipped (notes/metadata/unknown): {total_sheets - included}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
